// <auto-generated />
using System;
using MAVN.Service.CrossChainTransfers.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAVN.Service.CrossChainTransfers.MsSqlRepositories.Migrations
{
    [DbContext(typeof(CrossChainTransfersContext))]
    partial class CrossChainTransfersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cross_chain_transfers")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Service.CrossChainTransfers.MsSqlRepositories.Entities.DeduplicationEntity", b =>
                {
                    b.Property<string>("DeduplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("deduplication_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("Timestamp");

                    b.HasKey("DeduplicationId");

                    b.ToTable("deduplication_log");
                });
#pragma warning restore 612, 618
        }
    }
}
