// <auto-generated />
using System;
using MAVN.Service.CrossChainTransfers.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.CrossChainTransfers.MsSqlRepositories.Migrations
{
    [DbContext(typeof(CrossChainTransfersContext))]
    partial class CrossChainTransfersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cross_chain_transfers")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.CrossChainTransfers.MsSqlRepositories.Entities.DeduplicationEntity", b =>
                {
                    b.Property<string>("DeduplicationId")
                        .HasColumnName("deduplication_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DeduplicationId");

                    b.ToTable("deduplication_log");
                });
#pragma warning restore 612, 618
        }
    }
}
